### ISSUE TITLE
colab notebook pipeline error

### ISSUE THREAD

**Issue by CarloCattano** [Didgitaldoo/didge-lab#1]
Greetings, first of all thanks for your work on the matter and bringing such a tool to life !
I do get an error when trying chapter 3 on the notebook block 32 
```python
from cad.calc.pipeline import Pipeline, FinetuningPipelineStep, ExplorePipelineStep
from cad.calc.mutation import MutantPool, FinetuningMutator, ExploringMutator
from cad.ui.evolution_ui import EvolutionUI
from cad.ui.evolution_progress_bar import EvolutionProgressBar

# our mutant pool contains only a single mutant. we do not want to mutate several mutants
mutant_pool=MutantPool.create_from_father(parameters, 1, loss)

# here we define a processing pipeline
pipeline=Pipeline()
```
```python
---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

[<ipython-input-28-f4bfd650fe86>](https://localhost:8080/#) in <cell line: 10>()
      8 
      9 # here we define a processing pipeline
---> 10 pipeline=Pipeline()
     11 
     12 n_generations=100

2 frames

[/content/didge-lab/src/cad/common/app.py](https://localhost:8080/#) in get_config(cls, path)
    122             options = p.parse_known_args()[0]
    123 
--> 124             App.config=App.manager.dict()
    125             for key, value in vars(options).items():
    126                 App.config[key]=value

AttributeError: 'NoneType' object has no attribute 'dict'
```

Not sure if its a problem on my end but I followed the steps and read through and the rest was ok.

I would love to test some mutations to get to a certain desired output, and then print some tests in Berlin

**Comment by jnehring** [comment]
Congrats on getting so far! I created version 2.0 of didgelab and work with 2.0 only. but i documented only version 1.0 so i am not so super familiar with the older version anymore.

My first guess: Do you use the exact python version 3.8?

Please verify this before I try to help you further.

**Comment by CarloCattano** [comment]
You are right , collab reports 3.10
```python
!python -V

Python 3.10.12
```

I will try downgrading the python version and report back here

**Comment by CarloCattano** [comment]
Apparently colab is not happy with users trying to change their python version. I will try to see if I can research whats to be changed to make it work.

**Comment by jnehring** [comment]
I checked the codes and added two lines to make it work:

```
from cad.calc.pipeline import Pipeline, FinetuningPipelineStep, ExplorePipelineStep
from cad.calc.mutation import MutantPool, FinetuningMutator, ExploringMutator
from cad.ui.evolution_ui import EvolutionUI
from cad.ui.evolution_progress_bar import EvolutionProgressBar
from cad.common.app import App

App.full_init()

# our mutant pool contains only a single mutant. we do not want to mutate several mutants
mutant_pool=MutantPool.create_from_father(parameters, 1, loss)
# here we define a processing pipeline
pipeline=Pipeline()
```

The two new lines are

```
from cad.common.app import App

App.full_init()
```

Thanks for the bug report. I updated the Colab. Please let me know if this works for you.

**Comment by CarloCattano** [comment]
It works as expected now , thanks a lot !
